### ISSUE TITLE
strget opcode not working with p-field

### ISSUE THREAD

**Issue by flaviotordini** [nonameentername/godot-csound#4]
I'd like to pass a note name to my instrument as a string instead of a frequency. Something like this:

```csound
instr player
  iAmp = p4
  SNote = strget(p5)
  prints SNote
  iFreq = ntof:i(SNote)
  aOut = vco2:a(iAmp, iFreq)
  outall(aOut)
endin
```

When I run this in csound with a normal score or with `-L stdin`, it works. When run in godot-csound with `event_string`, `strget` returns the name of the instrument instead.

**Comment by nonameentername** [comment]
@flaviotordini could you provide more details on what command you are using for `event_string`?

**Comment by flaviotordini** [comment]
I reworked your example and come up with this code:

```gdscript
class_name Synth
extends Node2D

var csound: CsoundGodot

var csd: String

func _ready():
	CsoundServer.connect("csound_layout_changed", csound_layout_changed)

func csound_layout_changed():
	print("csound_layout_changed")
	csound = CsoundServer.get_csound("Main")
	csound.csound_ready.connect(csound_ready)

func csound_ready(csound_name):
	prints("Csound ready", csound_name)
	if csound_name != "Main": return
	csound.compile_orchestra(csd)

func maybeQuoteParam(p):
	if (p is String): p = '"' + p + '"'
	else: p = str(p)
	return p

func sendEvent(instr, duration: int, params: Array):
	var p1 = maybeQuoteParam(instr)

	var otherParams = params.map(func(p):
		return maybeQuoteParam(p)
	)

	var message = 'i' + p1 + ' 0 ' + str(duration) + ' ' + ' '.join(otherParams)
	prints("EVENT", message)
	csound.event_string(message)

func play(instr, params: Array):
	sendEvent(instr, -1, params)

func pause(instr):
	sendEvent(instr, 0, [])
```

**Comment by nonameentername** [comment]
@flaviotordini, there seems to be a bug in Csound that that is causing this error when using named instruments.
Can you try using a numbered instrument and see if you still get the error?

**Comment by flaviotordini** [comment]
Yes! It works with numbered instruments. Sorry to bother you with csound bugs. I tested with current stable csound and it didn't happen, so I thought it could be something with csound-godot.

**Comment by nonameentername** [comment]
@flaviotordini I was able to find the cause of this issue in csound and created a [pr](https://github.com/csound/csound/pull/2056) to resolve the error.
